### ISSUE TITLE
naming problem. provider means the one who is integrating to alif

### ISSUE THREAD

**Issue by nazrievfarrukhjon** [alifpay/providers#1]
alif is providing service the one who is integrating cannot be named provider. naming issue

**Comment by alifpay** [comment]
This is the Standard Protocol API for service providers who want their products or services to be available on Alif.mobi. By following this standard, providers enable their clients to make payments seamlessly via the platform. Providers need to implement their API according to these guidelines, ensuring that integration is straightforward with minimal setup—primarily through configuration settings.
